#!/usr/bin/env bash

export FOX_VANILLA_BUILD=1
export FOX_REMOVE_AAPT=1
export FOX_REMOVE_ZIP_BINARY=1
export FOX_NO_SAMSUNG_SPECIAL=1
export FOX_EXCLUDE_NANO_EDITOR=1
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export FOX_REMOVE_BASH=1
export FOX_DELETE_AROMAFM=1
export FOX_EXCLUDE_NANO_EDITOR=1
export FOX_EXCLUDE_APP_MANAGER=1
export FOX_USE_TAR_BINARY=0
export FOX_USE_SED_BINARY=0
export FOX_USE_BASH_SHELL=0
export FOX_USE_XZ_UTILS=0
