#!/usr/bin/env bash

export FOX_VANILLA_BUILD=1
export FOX_REMOVE_AAPT=1
export FOX_REMOVE_ZIP_BINARY=1
export FOX_NO_SAMSUNG_SPECIAL=1
export FOX_EXCLUDE_NANO_EDITOR=1
export FOX_DELETE_MAGISK_ADDON=1
